language: java
jdk:
- oraclejdk7
sudo: false
script: mvn clean install
after_success:
  - mvn clean test jacoco:report coveralls:report
  - .travis/before-deploy.sh
  - .travis/deploy.sh
cache:
  directories:
  - $HOME/.m2